server:
  port: ${SERVER_PORT:8080}

spring:
  application:
    name: stripe-webhook

  jackson:
    property-naming-strategy: SNAKE_CASE

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${SUPAHOST}:${SUPAPORT}/${SUPADATABASE}
    username: ${SUPAUSER}
    password: ${SUPAPASSWORD}
    hikari:
      minimum-idle: 2
      maximum-pool-size: 5
      connection-timeout: 20000
      idle-timeout: 90000
      max-lifetime: 600000
      keepalive-time: 300000
      pool-name: engine_pool_stripe-webhook

  jpa:
    hibernate:
      ddl-auto: none
    open-in-view: false
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        default_schema: public
        jdbc:
          lob:
            non_contextual_creation: true

stripe:
  secret-key: ${STRIPE_SECRET_KEY:}
  webhook-secret: ${STRIPE_WEBHOOK_SECRET:}
